stages:
  - test

test:
  image: cypress/base:14.17.0
  stage: test
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'main'
  script:
    # install dependencies
    - yarn ci
    # start the server in the background
    - yarn start:ci &
    # run Cypress tests
    - yarn test:e2e
