name: Code quality checks

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn ci

    - name: Lint
      run: yarn lint

    - name: Check types
      run: yarn type-check

    - name: Run unit tests
      run: yarn test

    - name: Run Cypress tests
      run: yarn test:e2e
